-- MySQL Script generated by MySQL Workbench
-- Tue May 25 19:10:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fastrack
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fastrack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastrack` DEFAULT CHARACTER SET utf8 ;
USE `fastrack` ;

-- -----------------------------------------------------
-- Table `fastrack`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastrack`.`user` ;

CREATE TABLE IF NOT EXISTS `fastrack`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `identifiant` VARCHAR(45) NULL DEFAULT NULL,
  `mdp` VARCHAR(40) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `role` ENUM("vendeur", "client") NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastrack`.`lobby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastrack`.`lobby` ;

CREATE TABLE IF NOT EXISTS `fastrack`.`lobby` (
  `id_lobby` INT(11) NOT NULL AUTO_INCREMENT,
  `name_lobby` VARCHAR(45) NULL DEFAULT NULL,
  `mdp_lobby` VARCHAR(45) NULL DEFAULT NULL,
  `nbr_player_lobby` VARCHAR(45) NULL DEFAULT NULL,
  `lobbycol` VARCHAR(45) NULL DEFAULT NULL,
  `id_user` INT(11) NOT NULL,
  PRIMARY KEY (`id_lobby`),
  INDEX `fk1_idx` (`id_user` ASC),
  CONSTRAINT `fk2`
    FOREIGN KEY (`id_user`)
    REFERENCES `fastrack`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastrack`.`partie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastrack`.`partie` ;

CREATE TABLE IF NOT EXISTS `fastrack`.`partie` (
  `idpartie` INT(11) NOT NULL AUTO_INCREMENT,
  `id_lobby` INT(11) NULL DEFAULT NULL,
  `J1` VARCHAR(1500) NULL DEFAULT NULL,
  `J2` VARCHAR(1500) NULL DEFAULT NULL,
  `J3` VARCHAR(1500) NULL DEFAULT NULL,
  `J4` VARCHAR(1500) NULL DEFAULT NULL,
  `J5` VARCHAR(1500) NULL DEFAULT NULL,
  PRIMARY KEY (`idpartie`),
  INDEX `fk1_idx` (`id_lobby` ASC),
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_lobby`)
    REFERENCES `fastrack`.`lobby` (`id_lobby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastrack`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastrack`.`chat` ;

CREATE TABLE IF NOT EXISTS `fastrack`.`chat` (
  `id_chat` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NULL,
  `message` VARCHAR(1500) NULL,
  PRIMARY KEY (`id_chat`),
  INDEX `fk3_idx` (`id_user` ASC),
  CONSTRAINT `fk3`
    FOREIGN KEY (`id_user`)
    REFERENCES `fastrack`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `fastrack`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `fastrack`;
INSERT INTO `fastrack`.`user` (`id_user`, `prenom`, `nom`, `identifiant`, `mdp`, `mail`, `role`) VALUES (1, 'Admin', 'Admin', 'Admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', 'admin@admin.fr', NULL);
INSERT INTO `fastrack`.`user` (`id_user`, `prenom`, `nom`, `identifiant`, `mdp`, `mail`, `role`) VALUES (2, 'Test', 'Test', 'Test', 'a94a8fe5ccb19ba61c4c0873d391e987982fbbd3', 'test@test.fr', NULL);
INSERT INTO `fastrack`.`user` (`id_user`, `prenom`, `nom`, `identifiant`, `mdp`, `mail`, `role`) VALUES (3, 'Test2', 'Test2', 'Test2', '109f4b3c50d7b0df729d299bc6f8e9ef9066971f', 'test2@test2.fr', NULL);

COMMIT;

